name: Delete Old Workflows

on:
  workflow_dispatch:
  schedule:
    - cron: 0 18 * * 1

jobs:
  Cleaning:
    runs-on: ubuntu-22.04

    steps:
    - name: Delete Old Workflows
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        retain_days: 16
        keep_minimum_runs: 2

    - name: Delete Old Releases
      uses: dev-drprasad/delete-older-releases@master
      with:
        keep_latest: 12
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
